#!/usr/bin/env python3
"""Fetch per-publication citation counts from Google Scholar and write them to
``_data/scholar_citations.yml``.

The publications page (``_pages/publications.md``) reads this data file and shows
the "Cited by N" count next to each paper, so the numbers stay consistent with
Google Scholar and update automatically — no manual editing required. This script
is meant to be run on a schedule by the GitHub Actions workflow
``.github/workflows/scholar-citations.yml``.

Each publication is keyed by a slug derived from its title. The slug is produced
the same way Jekyll's ``slugify`` filter (default mode) does, so the Liquid
template can look the entry up with ``{{ post.title | slugify }}``.
"""

import os
import re
import sys
import datetime
import unicodedata

import yaml

# Google Scholar user id. Defaults to this site's owner but can be overridden via
# the GOOGLE_SCHOLAR_ID environment variable (set in the workflow).
SCHOLAR_ID = os.environ.get("GOOGLE_SCHOLAR_ID", "50DhybsAAAAJ")

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(REPO_ROOT, "_data", "scholar_citations.yml")


def jekyll_slugify(value):
    """Replicate Jekyll's ``slugify`` filter (default mode).

    Lowercases the string and replaces every run of characters that are not
    Unicode letters or digits with a single hyphen, then trims leading/trailing
    hyphens.
    """
    value = unicodedata.normalize("NFKC", value or "").lower()
    # Keep Unicode letters/digits; turn every other run into a single hyphen.
    chars = [c if (c.isalnum()) else "-" for c in value]
    slug = re.sub(r"-+", "-", "".join(chars))
    return slug.strip("-")


def fetch_publications(scholar_id):
    """Return ``(total_citations, [publication dicts])`` from Google Scholar."""
    from scholarly import scholarly

    author = scholarly.search_author_id(scholar_id)
    author = scholarly.fill(author, sections=["publications", "indices"])

    publications = {}
    for pub in author.get("publications", []):
        bib = pub.get("bib", {})
        title = bib.get("title")
        if not title:
            continue
        slug = jekyll_slugify(title)
        if not slug:
            continue
        citation_id = pub.get("author_pub_id")
        url = None
        if citation_id:
            url = (
                "https://scholar.google.com/citations?view_op=view_citation"
                f"&hl=en&user={scholar_id}&citation_for_view={citation_id}"
            )
        entry = {
            "title": title,
            "citations": int(pub.get("num_citations", 0) or 0),
        }
        if url:
            entry["url"] = url
        # Keep the entry with the higher citation count if a slug collides.
        if slug not in publications or entry["citations"] > publications[slug]["citations"]:
            publications[slug] = entry

    total = int(author.get("citedby", 0) or 0)
    return total, publications


def main():
    try:
        total, publications = fetch_publications(SCHOLAR_ID)
    except Exception as exc:  # noqa: BLE001 - surface any scraping failure
        sys.stderr.write(f"Failed to fetch Google Scholar data: {exc}\n")
        return 1

    data = {
        "last_updated": datetime.date.today().isoformat(),
        "scholar_id": SCHOLAR_ID,
        "total_citations": total,
        "publications": publications,
    }

    header = (
        "# Google Scholar citation counts.\n"
        "# Auto-generated by markdown_generator/scholar_citations.py via the\n"
        "# .github/workflows/scholar-citations.yml workflow. Do not edit by hand.\n"
    )
    with open(OUTPUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(header)
        yaml.safe_dump(
            data,
            handle,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=True,
        )

    sys.stderr.write(
        f"Wrote {len(publications)} publications "
        f"({total} total citations) to {OUTPUT_PATH}\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
